name: test-run
on:
  workflow_dispatch:
jobs:
  test-env:
    runs-on: ubuntu-22.04
    steps:
      - name: Set Zip filename variable
        id: zipname
        run: |
          COMMIT_HASH=$(echo ${{ github.sha }} | cut -c1-8)
          echo $COMMIT_HASH
